classdef MissionControlView < handle
    
    %% Properties
    properties (Access = public)
        
        model
        
        figure
        
        % Launcher Settings
        launcherSettingsPanel
        springConstantLabel
        springConstantTextField
        projectileMassLabel
        projectileMassTextField
        
        % Simulation
        simulationPanel
        launchVelocityLabel
        launchVelocityTextField
        launchAngleLabel
        launchAngleTextField
        simulationDataTable
        trajectoryAxis
        
        % Predictions
        predictionsPanel
        targetDistanceLabel
        targetDistanceTextField
        predictionsCalculateButton
        predictionsExportButton
        predictionsTable
        
        % Tables
        tablesPanel
        launchVelocityTablesLabel
        launchVelocityTablesTextField
        tablesCalculateButton
        tablesExportButton
        angleTable
         
    end
    
    %% Non-static methods
    methods
        
        % Constructor
        function this = MissionControlView(model)
            this.model = model;
            
            % UIControl initialization
            units = 'characters';
            
            this.figure = figure(                                      ...
                                 'Units', units,                       ...
                                 'Position', [181 14.692 188 43.385],  ...
                                 'Name', 'Mission Control',            ...
                                 'NumberTitle', 'off',                 ...
                                 'MenuBar', 'none',                    ...
                                 'ToolBar', 'none');
                             
            this.launcherSettingsPanel = uipanel(                               ...
                                                 'Units', units,                ...
                                                 'Parent', this.figure,         ...
                                                 'Title', 'Launcher Settings',  ...
                                                 'Position', [1.67 35.54 46.0 6.92]);
            
            this.springConstantLabel = uicontrol(                                      ...
                                                 'Style', 'text',                      ...
                                                 'Parent', this.launcherSettingsPanel, ...
                                                 'Units', units,                       ...
                                                 'String', 'Spring Constant (N/m)',    ...
                                                 'FontSize', 14,                       ...
                                                 'HorizontalAlignment', 'left',        ...
                                                 'Position', [1.83 3.77 25.5 1.4]);
                                             
            this.springConstantTextField = uicontrol(                                      ...
                                                 'Style', 'edit',                      ...
                                                 'Parent', this.launcherSettingsPanel, ...
                                                 'Units', units,                       ...
                                                 'String', '',                         ...
                                                 'FontSize', 14,                       ...
                                                 'HorizontalAlignment', 'left',        ...
                                                 'Position', [26.17 3.69 17.33 1.695]);
                                             
            this.projectileMassLabel = uicontrol(                                      ...
                                                 'Style', 'text',                      ...
                                                 'Parent', this.launcherSettingsPanel, ...
                                                 'Units', units,                       ...
                                                 'String', 'Projectile Mass (kg)',    ...
                                                 'FontSize', 14,                       ...
                                                 'HorizontalAlignment', 'left',        ...
                                                 'Position', [1.83 1.0 25.5 1.4]);
                                             
            this.projectileMassTextField = uicontrol(                                  ...
                                                 'Style', 'edit',                      ...
                                                 'Parent', this.launcherSettingsPanel, ...
                                                 'Units', units,                       ...
                                                 'String', '',                         ...
                                                 'FontSize', 14,                       ...
                                                 'HorizontalAlignment', 'left',        ...
                                                 'Position', [26.17 .92 17.33 1.695]);                                  
        end
        
        % Getter and Setters
         
    end
end 
     
    